.TH INSECDEM 1 LOCAL

.SH NAME

insecdem - run various digital security demos

.SH SYNOPSIS

.B insecdem 

.SH AVAILABILITY

Linux

.SH DESCRIPTION

A wxGTK-based digital security demo suite. Provides simple front-end
to various sniffing, scanning and cracking tools for the benefit of
novice users trying to understand how digital security works without
the added complexity of advanced UIs.

.SH AUTHORS

 Smári McCarthy
 Chris Walker
 Samir Nassar
 D.G. Vole
